import {defineField, defineType} from 'sanity'

const targetAudienceOptions = [
  {title: 'Privatkunden', value: 'b2c'},
  {title: 'Geschäftskunden', value: 'b2b'},
  {title: 'Beide', value: 'both'},
]

export const appScreenType = defineType({
  name: 'appScreen',
  title: 'App Screen',
  type: 'document',
  groups: [
    {name: 'basis', title: 'Basis', default: true},
    {name: 'content', title: 'Inhalt'},
    {name: 'media', title: 'Medien'},
    {name: 'actions', title: 'Aktionen'},
    {name: 'settings', title: 'Einstellungen'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Interner Titel',
      type: 'string',
      group: 'basis',
      description: 'Interner Name im CMS, z. B. „Kundengruppe auswählen“.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'screenKey',
      title: 'Technischer Screen-Key',
      type: 'slug',
      group: 'basis',
      description: 'Muss mit dem Navigation-Step-Key übereinstimmen, z. B. „customer-selection“.',
      options: {source: 'title', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'screenType',
      title: 'Screen-Typ',
      type: 'string',
      group: 'basis',
      description: 'Legt fest, welche technische Screen-Komponente in der Web-App verwendet wird.',
      options: {
        list: [
          {title: 'Start / Hero', value: 'hero'},
          {title: 'Normale Inhaltsseite', value: 'content'},
          {title: 'Kundengruppe auswählen', value: 'customerSelection'},
          {title: 'Fragebogen / Beratung', value: 'questionnaire'},
          {title: 'Szenario-Matrix', value: 'scenarioMatrix'},
          {title: 'Szenario / Empfehlung', value: 'recommendation'},
          {title: 'Medien & Referenzen', value: 'mediaReferences'},
          {title: 'Dokumentauswahl', value: 'documentSelection'},
          {title: 'Kontakt / Lead-Erfassung', value: 'contact'},
          {title: 'AR / Scan', value: 'ar'},
          {title: 'Abschluss / Zusammenfassung', value: 'closing'},
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'contentPurpose',
      title: 'Inhaltlicher Zweck',
      type: 'string',
      group: 'basis',
      description: 'Beschreibt, wofür der Screen fachlich im Beratungsflow verwendet wird.',
      options: {
        list: [
          {title: 'Startseite', value: 'start'},
          {title: 'Intro', value: 'intro'},
          {title: 'Kundengruppe', value: 'customerGroup'},
          {title: 'Wer wir sind', value: 'about'},
          {title: 'Was wir bieten', value: 'offer'},
          {title: 'Vorteile / Nutzen', value: 'benefits'},
          {title: 'Ablauf / Prozess', value: 'process'},
          {title: 'Bedarf erfassen', value: 'needs'},
          {title: 'Beratungsmatrix', value: 'scenarioMatrix'},
          {title: 'Empfehlung', value: 'recommendation'},
          {title: 'Medien & Referenzen', value: 'mediaReferences'},
          {title: 'Dokumente / Unterlagen', value: 'salesDocuments'},
          {title: 'Kontakt', value: 'contact'},
          {title: 'Abschluss', value: 'closing'},
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'targetAudience',
      title: 'Zielgruppe',
      type: 'string',
      group: 'basis',
      description: 'Legt fest, ob der Screen für Privatkunden, Geschäftskunden oder beide gedacht ist.',
      options: {list: targetAudienceOptions, layout: 'radio'},
      initialValue: 'both',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'headline',
      title: 'Headline',
      type: 'string',
      group: 'content',
      description: 'Große sichtbare Überschrift im Screen.',
    }),
    defineField({
      name: 'subline',
      title: 'Subline',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'Kurzer Erklärungstext unter der Headline.',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero-Bild',
      type: 'image',
      group: 'media',
      options: {hotspot: true},
    }),
    defineField({
      name: 'heroMedia',
      title: 'Hero-Medium / Video optional',
      type: 'reference',
      group: 'media',
      to: [{type: 'mediaAsset'}],
      description: 'Optionales Bild, Video oder externer Link aus der Mediathek.',
    }),
    defineField({
      name: 'sections',
      title: 'Sections / Inhalte',
      type: 'array',
      group: 'content',
      description: 'Flexible Inhaltsbereiche für Text, Bild, Karten, Medien oder CTAs.',
      of: [
        {
          type: 'object',
          name: 'screenSection',
          title: 'Section',
          fields: [
            defineField({name: 'title', title: 'Section-Titel', type: 'string'}),
            defineField({name: 'eyebrow', title: 'Kleines Label / Eyebrow', type: 'string'}),
            defineField({name: 'text', title: 'Text', type: 'text', rows: 5}),
            defineField({name: 'image', title: 'Bild', type: 'image', options: {hotspot: true}}),
            defineField({
              name: 'media',
              title: 'Medium / Video optional',
              type: 'reference',
              to: [{type: 'mediaAsset'}],
            }),
            defineField({
              name: 'visibleFor',
              title: 'Sichtbar für',
              type: 'string',
              description: 'Damit einzelne Sections je nach B2B/B2C unterschiedlich angezeigt werden können.',
              options: {list: targetAudienceOptions, layout: 'radio'},
              initialValue: 'both',
            }),
            defineField({
              name: 'layout',
              title: 'Layout',
              type: 'string',
              options: {
                list: [
                  {title: 'Text', value: 'text'},
                  {title: 'Text + Bild', value: 'textImage'},
                  {title: 'Karten', value: 'cards'},
                  {title: 'Medien / Video', value: 'media'},
                  {title: 'Vergleich / Matrix', value: 'comparison'},
                  {title: 'Timeline / Prozess', value: 'timeline'},
                  {title: 'CTA', value: 'cta'},
                ],
              },
              initialValue: 'text',
            }),
            defineField({name: 'sortOrder', title: 'Reihenfolge', type: 'number', initialValue: 0}),
          ],
          preview: {
            select: {title: 'title', subtitle: 'layout', media: 'image'},
            prepare({title, subtitle, media}) {
              return {
                title: title || 'Unbenannte Section',
                subtitle: subtitle ? `Layout: ${subtitle}` : 'Keine Layout-Auswahl',
                media,
              }
            },
          },
        },
      ],
    }),
    defineField({
      name: 'primaryCta',
      title: 'Primärer CTA',
      type: 'object',
      group: 'actions',
      fields: [
        defineField({name: 'label', title: 'Button-Text', type: 'string'}),
        defineField({
          name: 'target',
          title: 'Ziel / Route',
          type: 'string',
          description: 'Z. B. „next“, „back“ oder ein Screen-Key wie „customer-selection“.',
        }),
      ],
    }),
    defineField({
      name: 'secondaryCta',
      title: 'Sekundärer CTA',
      type: 'object',
      group: 'actions',
      fields: [
        defineField({name: 'label', title: 'Button-Text', type: 'string'}),
        defineField({name: 'target', title: 'Ziel / Route', type: 'string'}),
      ],
    }),
    defineField({name: 'sortOrder', title: 'Reihenfolge', type: 'number', group: 'settings', initialValue: 0}),
    defineField({name: 'isActive', title: 'Aktiv', type: 'boolean', group: 'settings', initialValue: true}),
  ],
  orderings: [{title: 'Reihenfolge', name: 'sortOrderAsc', by: [{field: 'sortOrder', direction: 'asc'}]}],
  preview: {
    select: {
      title: 'title',
      screenType: 'screenType',
      contentPurpose: 'contentPurpose',
      targetAudience: 'targetAudience',
      media: 'heroImage',
    },
    prepare({title, screenType, contentPurpose, targetAudience, media}) {
      return {
        title: title || 'Unbenannter Screen',
        subtitle: `${screenType || 'kein Typ'} · ${contentPurpose || 'kein Zweck'} · ${targetAudience || 'keine Zielgruppe'}`,
        media,
      }
    },
  },
})
